# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'

env:
  GEMINI_API_KEY: AIzaSyBrqjbGbuPoKiPgOktseFe61eMHWXILceg

providers:
  - "google:gemini-2.5-flash-lite"
  - "google:gemini-2.5-flash"
    

tests: file://tests/casos.yaml